version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports: 
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  api:
    container_name: market_api
    restart: always
    image: arpit5492/market-verse:market-api-latest
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    env_file:
      - ./backend-server/.env
    ports: 
      - "4000:4000"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend-server
          target: /usr/src/api
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend-server/package.json
  
  client:
    container_name: market_client
    restart: always
    image: arpit5492/market-verse:market-client-latest
    build:
      context: ./UI-design/frontend-server
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./UI-design/frontend-server
          target: /usr/src/client
          ignore:
            - node_modules/
        - action: rebuild
          path: ./UI-design/frontend-server/package.json